/*
 * Copyright 2020 American Express Travel Related Services Company, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */

package com.aexp.blaze.bloom.beans;

import java.io.Serializable;

public class JobDetails implements Serializable {

    /**
     * The source of the input (csv/hive)
     */
    private String sourceType;
    /**
     * he name of file. e.g. INPUT.*.CSV
     */
    private String inputFilePath;
    /**
     * The destination table in MemSQL
     */
    private String tableName;
    /**
     * Total number of records in file.
     */
    private String inputRecordsCount;
    /**
     * Total number of records finally generated by Job
     */
    private String processedRecordsCount;
    /**
     * Time when job started
     */
    private String startTime;
    /**
     * Time when job ended
     */
    private String endTime;
    /**
     * Type of Load(FULL_REFRESH,UPSERT)
     */
    private String refreshType;
    /**
     * Fully Qualified Class name
     */
    private String className;

    /**
     * Yarn applicationId for the Job
     */
    private String applicationId;

    private String totalTimeTaken;

    private String status;

    private String errorMessage;

    private String loadAppendTimestampCol;

    public String getSourceType() {
        return sourceType;
    }

    public void setSourceType(String sourceType) {
        this.sourceType = sourceType;
    }

    public String getInputFilePath() {
        return inputFilePath;
    }

    public void setInputFilePath(String inputFilePath) {
        this.inputFilePath = inputFilePath;
    }

    public String getTotalTimeTaken() {
        return totalTimeTaken;
    }

    public void setTotalTimeTaken(String totalTimeTaken) {
        this.totalTimeTaken = totalTimeTaken;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public String getErrorMessage() {
        return errorMessage;
    }

    public void setErrorMessage(String errorMessage) {
        this.errorMessage = errorMessage;
    }

    public String getTableName() {
        return tableName;
    }

    public void setTableName(String tableName) {
        this.tableName = tableName;
    }


    public String getInputRecordsCount() {
        return inputRecordsCount;
    }

    public void setInputRecordsCount(String inputRecordsCount) {
        this.inputRecordsCount = inputRecordsCount;
    }

    public String getProcessedRecordsCount() {
        return processedRecordsCount;
    }

    public void setProcessedRecordsCount(String processedRecordsCount) {
        this.processedRecordsCount = processedRecordsCount;
    }

    public String getStartTime() {
        return startTime;
    }

    public void setStartTime(String startTime) {
        this.startTime = startTime;
    }

    public String getEndTime() {
        return endTime;
    }

    public void setEndTime(String endTime) {
        this.endTime = endTime;
    }

    public String getApplicationId() {
        return applicationId;
    }

    public void setApplicationId(String applicationId) {
        this.applicationId = applicationId;
    }

    public String getRefreshType() {
        return refreshType;
    }

    public void setRefreshType(String refreshType) {
        this.refreshType = refreshType;
    }

    public String getClassName() {
        return className;
    }

    public void setClassName(String className) {
        this.className = className;
    }

    public String getLoadAppendTimestampCol() {
        return loadAppendTimestampCol;
    }

    public void setLoadAppendTimestampCol(String loadAppendTimestampCol) {
        this.loadAppendTimestampCol = loadAppendTimestampCol;
    }
}